# Generated by Django 4.2.3 on 2023-07-06 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_actor_author_category_company_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author'),
        ),
        migrations.AddField(
            model_name='manga',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../default_icons/image_missing.png', upload_to='icons/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_anime_favorites',
            field=models.ManyToManyField(blank=True, to='main.anime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_manga_favorites',
            field=models.ManyToManyField(blank=True, to='main.manga'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 23, 25, 20, 868897), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manga',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 23, 25, 20, 868897), primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(blank=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('anime', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('manga', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
