# Generated by Django 4.2.3 on 2023-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_anime_alter_review_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('anime__isnull', True), ('manga__isnull', False)), models.Q(('anime__isnull', False), ('manga__isnull', True)), _connector='OR'), name='One content required for single review'),
        ),
    ]
