# Generated by Django 4.2.3 on 2023-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_animecomment_animereview_mangacomment_mangareview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_anime_favorites',
            field=models.ManyToManyField(blank=True, related_name='anime_favorites', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_anime_reviews',
            field=models.ManyToManyField(blank=True, related_name='anime_reviews', through='main.AnimeReview', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_manga_favorites',
            field=models.ManyToManyField(blank=True, related_name='manga_favorites', to='main.manga'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_manga_reviews',
            field=models.ManyToManyField(blank=True, related_name='manga_reviews', through='main.MangaReview', to='main.manga'),
        ),
    ]
