# Generated by Django 4.2.3 on 2023-07-06 17:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('topic', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateField()),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('topic', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateField()),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манга',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 20, 40, 49, 278706), primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(blank=True)),
                ('anime', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('manga', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created'],
            },
        ),
    ]
