# Generated by Django 4.2.3 on 2023-07-06 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автор',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../default_icons/image_missing.jpg', upload_to='icons')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created', models.DateField()),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='topic',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='topic',
            new_name='name',
        ),
        migrations.AddField(
            model_name='anime',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.manga'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='../default_icons/image_missing.jpg', upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 46, 9, 961017), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(default='../default_icons/image_missing.jpg', upload_to='icons'),
        ),
        migrations.AddField(
            model_name='anime',
            name='actors',
            field=models.ManyToManyField(to='main.actor'),
        ),
        migrations.AddField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author'),
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
        migrations.AddField(
            model_name='anime',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company'),
        ),
        migrations.AddField(
            model_name='manga',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
        migrations.AddField(
            model_name='manga',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company'),
        ),
    ]
